name: jenkins-docker

services:
  jenkins:
    image: jenkins/jenkins:2.452.2-lts-jdk17
    container_name: jenkins
    hostname: jenkins
    restart: always
    ports:
      - 50000:50000
    volumes:
      - ${JENKINS_DATA_DIR}:/var/jenkins_home
      - ./init.groovy:/usr/share/jenkins/ref/init.groovy.d/create-admin-user.groovy
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    env_file:
      - .env

  nginx:
    image: nginx:1.27.0-alpine3.19
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    env_file:
      - .env
    depends_on:
      - jenkins
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    user: root
    ports:
      - 9100:9100
    depends_on:
      - jenkins
      - nginx
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
